- hosts: all
  become: true

  tasks:
    - name: Install apt-transport-https
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: latest

    - name: Check if "Google" keyring is already installed
      ansible.builtin.stat:
        path: "/etc/apt/keyrings/google.gpg"
      register: google_keyring

    - name: Install "Google" keyring
      block:
        - name: Download "Google" signing key
          ansible.builtin.get_url:
            url: "https://dl.google.com/linux/linux_signing_key.pub"
            dest: "/tmp/google.gpg"
        - name: Add "Google" signing key
          ansible.builtin.shell:
            cmd: "cat /tmp/google.gpg | gpg --dearmor -o /etc/apt/keyrings/google.gpg"
        - name: Remove temporary files from "Google" signing key
          ansible.builtin.file:
            path: "/tmp/google.gpg"
            state: absent
      when: google_keyring is defined and not google_keyring.stat.exists

    - name: Check if "Google Chrome" repository is already installed
      ansible.builtin.stat:
        path: "/etc/apt/sources.list.d/google-chrome.list"
      register: chrome_repository

    - name: Install "Google Chrome" repository
      block:
        - name: Get DEB architecture
          shell: dpkg --print-architecture
          register: deb_architecture

        - name: Add "Google Chrome" repository into sources list
          ansible.builtin.apt_repository:
            repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/etc/apt/keyrings/google.gpg] http://dl.google.com/linux/chrome/deb/ stable main"
            filename: google-chrome
            state: present
      when: chrome_repository is defined and not chrome_repository.stat.exists

    - name: Install "Google Chrome" packages
      ansible.builtin.apt:
        name: google-chrome-stable
        state: latest
        update_cache: true
